stages:
  - build
  - deploy

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker-compose build
  only:
    - main

deploy:
  stage: deploy
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - apk add --no-cache openssh-client git
    - eval $(ssh-agent -s)
    - chmod 400 $SSH_KEY
    - ssh-add $SSH_KEY
  script:
    - ssh -v -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
      cd /opt/docker/custom-errors &&
      git pull origin main &&
      docker-compose down &&
      docker-compose up -d --build &&
      docker-compose ps &&
      docker-compose logs -f"
  only:
    - main
  environment:
    name: production
  when: manual # กด deploy ได้เองใน GitLab
